services:
  deepwiki:
    build: .
    ports:
      - "${PORT:-8173}:${PORT:-8173}" # API port
      - "3133:3133" # Next.js port
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8173}
      - NODE_ENV=production
      - SERVER_BASE_URL=http://localhost:${PORT:-8173}
    volumes:
      - ~/.adalflow:/root/.adalflow # Persist repository and embedding data

    # Resource limits for docker-compose up (not Swarm mode)
    mem_limit: 6g
    mem_reservation: 2g
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8001}/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - agoryx-network

networks:
  agoryx-network:
    driver: bridge
    external: true
    name: agoryx-network
